name: Test de Actions
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ master ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
      - name: Mocha
        run: |
          npm install
          npm test
